# kin-emoji-picker
# run kin-emoji-picker
unbind = SUPER_CTRL, E
bind = SUPER_CTRL, E, exec, /home/karthik/Applications/kin-emoji-picker_0.1.0_amd64_46664bd2750f04c15efc7a3acf44c087.AppImage

# https://github.com/bjarneo/omarchy-jot
# shortcut key for jot.
bindd = SUPER SHIFT, J, Jot, exec, uwsm app -- jot
# windowrule for jot.
windowrule = match:class com.github.jot, float on

# window rules for impala and bluetui
windowrule = match:class local.wlctl, float on
windowrule = match:class local.bluetui, float on

# https://github.com/JamDon2/hyprquickshot
bind = SUPER SHIFT, A, exec, quickshell -c hyprquickshot -n

# https://github.com/Grenish/clipboard-manager
bind = SUPER, V, exec, ~/.local/share/clipboard-manager/trigger.sh
# Hyprland v0.53+ Manual Config
windowrule = float on, match:class floating-clipboard

# vicinae setup
unbind = SUPER, SPACE

bind = SUPER, Space, exec, vicinae toggle
# bind = SUPER, Space, exec, walker

misc {
    focus_on_activate = true
}

windowrule = match:class kitty, no_blur on
