
plugin {
    hyprtrails {
        color = rgba(00ffffff)
    }
}
# kin-emoji-picker
# kin-emoji-picker
windowrulev2 = float, class:^(kin-emoji-picker)$
windowrulev2 = pin, class:^(kin-emoji-picker)$
windowrulev2 = size 400 400, class:^(kin-emoji-picker)$
windowrulev2 = move 0 0, class:^(kin-emoji-picker)$
#
# windowrule for jot.
windowrulev2 = float, class:^(com.github.jot)$


# run kin-emoji-picker
unbind = SUPER_CTRL, E
bind = SUPER_CTRL, E, exec, /home/karthik/Applications/kin-emoji-picker_0.1.0_amd64_46664bd2750f04c15efc7a3acf44c087.AppImage

# shortcut key for jot.
bindd = SUPER SHIFT, J, Jot, exec, uwsm app -- jot

# window rules for impala and bluetui
# windowrulev2 = float, class:^(local.impala)$
windowrule = match:class local.impala, float on
# windowrulev2 = float, class:^(local.bluetui)$
windowrule = match:class local.bluetui, float on

bind = SUPER SHIFT, A, exec, quickshell -c hyprquickshot -n

