-- Change the default Omarchy look'n'feel.

-- https://wiki.hypr.land/Configuring/Basics/Variables/#general
-- hl.config({
--   general = {
--     -- No gaps between windows or borders.
--     gaps_in = 0,
--     gaps_out = 0,
--     border_size = 0,
--
--     -- Change to niri-like side-scrolling layout.
--     layout = "scrolling",
--   },
-- })

-- https://wiki.hypr.land/Configuring/Basics/Variables/#decoration
-- hl.config({
--   decoration = {
--     -- Use round window corners.
--     rounding = 8,
--
--     -- Dim unfocused windows (0.0 = no dim, 1.0 = fully dimmed).
--     dim_inactive = true,
--     dim_strength = 0.15,
--   },
-- })

-- https://wiki.hypr.land/Configuring/Basics/Variables/#animations
-- hl.config({
--   animations = {
--     -- Disable all animations.
--     enabled = false,
--   },
-- })

-- https://wiki.hypr.land/Configuring/Basics/Variables/#layout
-- hl.config({
--   layout = {
--     -- Avoid overly wide single-window layouts on wide screens.
--     single_window_aspect_ratio = { 1, 1 },
--   },
-- })

-- https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/
-- hl.config({
--   scrolling = {
--     -- See only one column per screen instead of two.
--     column_width = 0.97,
--   },
-- })

-- Change the default Omarchy look'n'feel

-- https://wiki.hyprland.org/Configuring/Variables/#general
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.curve("wind", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1 } } })
hl.curve("winIn", { type = "bezier", points = { { 0.1, 1.05 }, { 0.1, 1 } } })
hl.curve("winOut", { type = "bezier", points = { { 0.3, -0.3 }, { 0.1, 1 } } })
hl.curve("liner", { type = "bezier", points = { { 1, 1 }, { 1, 1 } } })
hl.animation({
	leaf = "windows",
	enabled = true,
	speed = 6,
	bezier = "wind",
	style = "slide",
})
hl.animation({
	leaf = "windowsIn",
	enabled = true,
	speed = 6,
	bezier = "winIn",
	style = "slide",
})
hl.animation({
	leaf = "windowsOut",
	enabled = true,
	speed = 5,
	bezier = "winOut",
	style = "slide",
})
hl.animation({
	leaf = "windowsMove",
	enabled = true,
	speed = 5,
	bezier = "wind",
	style = "slide",
})
hl.animation({
	leaf = "border",
	enabled = true,
	speed = 1,
	bezier = "liner",
})
hl.animation({
	leaf = "fade",
	enabled = true,
	speed = 10,
	bezier = "default",
})
hl.animation({
	leaf = "workspaces",
	enabled = true,
	speed = 5,
	bezier = "wind",
})
hl.config({
	general = {
		-- No gaps between windows
		gaps_in = 2,
		gaps_out = 0,
		-- Use master layout instead of dwindle
		-- layout = scrolling
	},
	-- https://wiki.hyprland.org/Configuring/Variables/#decoration
	decoration = {
		-- Use round window corners
		rounding = 4,
		active_opacity = 0.97,
		inactive_opacity = 0.9,
		-- https://wiki.hyprland.org/Configuring/Variables/#blur
		-- blur = {
		--	enabled = true,
		--	size = 5,
		--	passes = 4, -- more passes =  more smooth blur
		-- these blur apply to windows whose opacity is < 1.
		-- vibrancy = 0.1396, -- this gives a macos like frosted glass look to the blur.
		-- },
	},
	cursor = {
		enable_hyprcursor = true,
	},
	animations = {
		enabled = true,
		-- bezier is the easing curve.
		-- animation for windows behaviour.
	},
})
