console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[palette]
black = '#262B44'
blue = '#4B95E9'
green = '#59C9A5'
orange = '#F07623'
red = '#D81E5B'
yellow = '#F3AE35'
os = "#ACB0BE"
pink = '#F5BDE6'
lavender = '#B7BDF8'
white = '#FFFFFF'
text = '#494D64'

[transient_prompt]
foreground_templates = [
"{{if gt .Code 0}}p:red{{end}}",
"{{if eq .Code 0}}p:green{{end}}"
]
background = 'transparent'
template = '⇛ '

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = 'path'
style = 'plain'
background = 'transparent'
foreground = 'p:lavender'

[blocks.segments.properties]
style = 'full'

[[blocks.segments]]
type = 'git'
style = 'plain'
foreground = '#6c6c6c'
background = 'transparent'
template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{end}} '

[blocks.segments.properties]
branch_icon = ''
commit_icon = '@'

[[blocks.segments]]
type = 'text'
style = 'plain'
foreground_templates = [
"{{if gt .Code 0}}p:red{{end}}",
"{{if eq .Code 0}}p:green{{end}}"
]
background = 'transparent'
template = '⟩'

[[blocks]]
type = 'rprompt'
overflow = 'hidden'

[[blocks.segments]]
type = 'executiontime'
style = 'plain'
foreground = 'yellow'
background = 'transparent'
template = '{{ .FormattedMs }}'

[secondary_prompt]
foreground = 'p:green'
background = 'transparent'
template = '⟩⟩ '

