unbind r
bind r source-file ~/.tmux.conf

set -g mouse on
set -g prefix C-s # set ctrl + s as prefix

setw -g mode-keys vi
bind-key h select-pane -L
bind-key l select-pane -R
bind-key k select-pane -U
bind-key j select-pane -D

# Resize panes using vim-style keys (Ctrl + h/j/k/l)
bind -r C-h resize-pane -L 5
bind -r C-j resize-pane -D 5
bind -r C-k resize-pane -U 5
bind -r C-l resize-pane -R 5

# Enable extended keys for tmux
set -s extended-keys on

# Allows Shift+Enter, Ctrl+Shift+<key>, etc. to work correctly in apps
set -as terminal-features 'kitty:extkeys'

# Set the default terminal inside tmux
# This ensures applications (like Neovim) know they can use 256 colors/RGB
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-kitty:RGB"

# Split panes with | and -
unbind %
bind | split-window -h   # Horizontal split with |
unbind '"'
bind - split-window -v   # Vertical split with -

# Use vi keybindings in copy mode
set-window-option -g mode-keys vi

# Start text selection in copy mode with 'v'
bind-key -T copy-mode-vi 'v' send -X begin-selection

# Copy selected text with 'y'
bind-key -T copy-mode-vi 'y' send -X copy-selection

# Open new windows and splits in the same directory
bind c new-window -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
bind '-' split-window -v -c "#{pane_current_path}"

set-option -g status-position top
set -g default-terminal "tmux-256color"

# copy text to clipboard as soon as the mouse selection stops.
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -i"

# Add plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on' # restore last saved tmux sessions
set -g @plugin 'nhdaly/tmux-better-mouse-mode'


# Start counting windows and panes at 1 instead of 0
set -g base-index 1
setw -g pane-base-index 1

# Maximize/minimize the current pane with 'm'
unbind z
unbind m
bind m resize-pane -Z

# Bind 'x' to kill the current pane
bind x kill-pane

# Re-number windows automatically when one is closed
# (This prevents gaps like 1, 2, 4, 5)
set -g renumber-windows on

# switch windows alt+number
bind-key -n M-1 select-window -t 0
bind-key -n M-2 select-window -t 1
bind-key -n M-3 select-window -t 2
bind-key -n M-4 select-window -t 3
bind-key -n M-5 select-window -t 4
bind-key -n M-6 select-window -t 5
bind-key -n M-7 select-window -t 6
bind-key -n M-8 select-window -t 7
bind-key -n M-9 select-window -t 8

set -ga terminal-overrides ",*256col*:Tc" # If the terminal supports 256 colors, force-enable 24-bit RGB colors.

set  -s escape-time 0 # Don’t wait. If I press Esc, assume I meant it. neovim feels snapppy

# Initialize TPM
run '~/.tmux/plugins/tpm/tpm'

